// BTG Pactual Day Trade Asset List
// Source: https://investimentos.btgpactual.com/renda-variavel/day-trade/lista-de-ativos

export interface BTGAsset {
  ticker: string;
  marginPerShare: number; // Margem em R$ por ação
  leverage: number; // Alavancagem (ex: 105, 98, 20, 5, 1)
}

export const btgAssets: BTGAsset[] = [
  // Alta alavancagem (90x+)
  { ticker: 'CPLE3', marginPerShare: 0.13, leverage: 105 },
  { ticker: 'EMBJ3', marginPerShare: 1.00, leverage: 103 },
  { ticker: 'MBRF3', marginPerShare: 0.19, leverage: 103 },
  { ticker: 'EQTL3', marginPerShare: 0.41, leverage: 101 },
  { ticker: 'JBSS32', marginPerShare: 0.80, leverage: 101 },
  { ticker: 'WEGE3', marginPerShare: 0.52, leverage: 101 },
  { ticker: 'BPAC11', marginPerShare: 0.62, leverage: 100 },
  { ticker: 'DIRR3', marginPerShare: 0.14, leverage: 100 },
  { ticker: 'ENGI11', marginPerShare: 0.53, leverage: 100 },
  { ticker: 'MOTV3', marginPerShare: 0.17, leverage: 100 },
  { ticker: 'RADL3', marginPerShare: 0.25, leverage: 100 },
  { ticker: 'RAIL3', marginPerShare: 0.15, leverage: 100 },
  { ticker: 'UGPA3', marginPerShare: 0.25, leverage: 100 },
  { ticker: 'ABEV3', marginPerShare: 0.15, leverage: 99 },
  { ticker: 'BBAS3', marginPerShare: 0.25, leverage: 99 },
  { ticker: 'BOVV11', marginPerShare: 1.90, leverage: 99 },
  { ticker: 'CYRE3', marginPerShare: 0.30, leverage: 99 },
  { ticker: 'ITSA4', marginPerShare: 0.14, leverage: 99 },
  { ticker: 'ITUB4', marginPerShare: 0.46, leverage: 99 },
  { ticker: 'RDOR3', marginPerShare: 0.44, leverage: 99 },
  { ticker: 'SBSP3', marginPerShare: 1.42, leverage: 99 },
  { ticker: 'SMAL11', marginPerShare: 1.27, leverage: 99 },
  { ticker: 'SUZB3', marginPerShare: 0.52, leverage: 99 },
  { ticker: 'TOTS3', marginPerShare: 0.47, leverage: 99 },
  { ticker: 'VBBR3', marginPerShare: 0.29, leverage: 99 },
  { ticker: 'ALOS3', marginPerShare: 0.31, leverage: 98 },
  { ticker: 'BOVA11', marginPerShare: 1.81, leverage: 98 },
  { ticker: 'ENEV3', marginPerShare: 0.22, leverage: 98 },
  { ticker: 'GGBR4', marginPerShare: 0.24, leverage: 98 },
  { ticker: 'PETR4', marginPerShare: 0.37, leverage: 98 },
  { ticker: 'SMFT3', marginPerShare: 0.23, leverage: 98 },
  { ticker: 'TIMS3', marginPerShare: 0.25, leverage: 98 },
  { ticker: 'TSLA34', marginPerShare: 0.71, leverage: 98 },
  { ticker: 'VALE3', marginPerShare: 0.87, leverage: 98 },
  { ticker: 'VIVT3', marginPerShare: 0.38, leverage: 98 },
  { ticker: 'AXIA6', marginPerShare: 0.59, leverage: 97 },
  { ticker: 'AXIA7', marginPerShare: 0.54, leverage: 97 },
  { ticker: 'BBDC4', marginPerShare: 0.22, leverage: 97 },
  { ticker: 'BBSE3', marginPerShare: 0.38, leverage: 97 },
  { ticker: 'CMIG4', marginPerShare: 0.12, leverage: 97 },
  { ticker: 'KLBN11', marginPerShare: 0.20, leverage: 97 },
  { ticker: 'MULT3', marginPerShare: 0.33, leverage: 97 },
  { ticker: 'PETR3', marginPerShare: 0.40, leverage: 97 },
  { ticker: 'RENT3', marginPerShare: 0.49, leverage: 97 },
  { ticker: 'ASAI3', marginPerShare: 0.09, leverage: 96 },
  { ticker: 'AXIA3', marginPerShare: 0.56, leverage: 96 },
  { ticker: 'BRAV3', marginPerShare: 0.19, leverage: 96 },
  { ticker: 'CEAB3', marginPerShare: 0.12, leverage: 96 },
  { ticker: 'MGLU3', marginPerShare: 0.10, leverage: 96 },
  { ticker: 'PRIO3', marginPerShare: 0.51, leverage: 96 },
  { ticker: 'SANB11', marginPerShare: 0.38, leverage: 96 },
  { ticker: 'B3SA3', marginPerShare: 0.17, leverage: 95 },
  { ticker: 'LREN3', marginPerShare: 0.16, leverage: 95 },
  { ticker: 'POMO4', marginPerShare: 0.07, leverage: 94 },
  
  // Média alavancagem (10x-90x)
  { ticker: 'CSAN3', marginPerShare: 0.07, leverage: 83 },
  { ticker: 'COGN3', marginPerShare: 0.07, leverage: 65 },
  { ticker: 'CPFE3', marginPerShare: 2.65, leverage: 21 },
  { ticker: 'BBDC3', marginPerShare: 0.93, leverage: 20 },
  { ticker: 'BEEF3', marginPerShare: 0.31, leverage: 20 },
  { ticker: 'CSMG3', marginPerShare: 2.57, leverage: 20 },
  { ticker: 'CSNA3', marginPerShare: 0.54, leverage: 20 },
  { ticker: 'CURY3', marginPerShare: 1.75, leverage: 20 },
  { ticker: 'NATU3', marginPerShare: 0.44, leverage: 20 },
  { ticker: 'NEOE3', marginPerShare: 1.62, leverage: 20 },
  { ticker: 'NVDC34', marginPerShare: 1.04, leverage: 20 },
  { ticker: 'PSSA3', marginPerShare: 2.49, leverage: 20 },
  { ticker: 'TAEE11', marginPerShare: 2.16, leverage: 20 },
  { ticker: 'VIVA3', marginPerShare: 1.38, leverage: 20 },
  { ticker: 'INBR32', marginPerShare: 2.65, leverage: 19 },
  { ticker: 'AZZA3', marginPerShare: 1.83, leverage: 15 },
  { ticker: 'BRAP4', marginPerShare: 1.65, leverage: 15 },
  { ticker: 'GOAU4', marginPerShare: 0.70, leverage: 15 },
  { ticker: 'HYPE3', marginPerShare: 1.74, leverage: 15 },
  { ticker: 'MELI34', marginPerShare: 6.63, leverage: 15 },
  { ticker: 'MRVE3', marginPerShare: 0.55, leverage: 15 },
  { ticker: 'USIM5', marginPerShare: 0.46, leverage: 14 },
  { ticker: 'AURA33', marginPerShare: 12.52, leverage: 10 },
  { ticker: 'AURE3', marginPerShare: 1.17, leverage: 10 },
  { ticker: 'CXSE3', marginPerShare: 1.76, leverage: 10 },
  { ticker: 'ECOR3', marginPerShare: 1.22, leverage: 10 },
  { ticker: 'EGIE3', marginPerShare: 3.35, leverage: 10 },
  { ticker: 'FLRY3', marginPerShare: 1.71, leverage: 10 },
  { ticker: 'GGPS3', marginPerShare: 1.91, leverage: 10 },
  { ticker: 'GMAT3', marginPerShare: 0.50, leverage: 10 },
  { ticker: 'IGTI11', marginPerShare: 2.88, leverage: 10 },
  { ticker: 'ISAE4', marginPerShare: 2.84, leverage: 10 },
  { ticker: 'MOVI3', marginPerShare: 1.23, leverage: 10 },
  { ticker: 'PCAR3', marginPerShare: 0.38, leverage: 10 },
  { ticker: 'RECV3', marginPerShare: 1.15, leverage: 10 },
  { ticker: 'ROXO34', marginPerShare: 1.63, leverage: 10 },
  { ticker: 'SAPR11', marginPerShare: 4.79, leverage: 10 },
  { ticker: 'XPBR31', marginPerShare: 10.71, leverage: 10 },
  { ticker: 'YDUQ3', marginPerShare: 1.47, leverage: 10 },
  { ticker: 'TEND3', marginPerShare: 2.70, leverage: 9 },
  
  // Baixa alavancagem (5x)
  { ticker: 'ALPA4', marginPerShare: 2.76, leverage: 5 },
  { ticker: 'ALUP11', marginPerShare: 6.84, leverage: 5 },
  { ticker: 'AMZO34', marginPerShare: 12.63, leverage: 5 },
  { ticker: 'ANIM3', marginPerShare: 1.05, leverage: 5 },
  { ticker: 'BRKM5', marginPerShare: 1.94, leverage: 5 },
  { ticker: 'CBAV3', marginPerShare: 2.03, leverage: 5 },
  { ticker: 'CMIN3', marginPerShare: 1.28, leverage: 5 },
  { ticker: 'CVCB3', marginPerShare: 0.53, leverage: 5 },
  { ticker: 'CYRE4', marginPerShare: 5.75, leverage: 5 },
  { ticker: 'EZTC3', marginPerShare: 3.13, leverage: 5 },
  { ticker: 'GOGL34', marginPerShare: 29.18, leverage: 5 },
  { ticker: 'GRND3', marginPerShare: 0.98, leverage: 5 },
  { ticker: 'INTB3', marginPerShare: 2.45, leverage: 5 },
  { ticker: 'IRBR3', marginPerShare: 12.04, leverage: 5 },
  { ticker: 'ITUB3', marginPerShare: 8.61, leverage: 5 },
  { ticker: 'JHSF3', marginPerShare: 1.91, leverage: 5 },
  { ticker: 'KEPL3', marginPerShare: 2.09, leverage: 5 },
  { ticker: 'M1TA34', marginPerShare: 25.75, leverage: 5 },
  { ticker: 'M2ST34', marginPerShare: 2.38, leverage: 5 },
  { ticker: 'MDNE3', marginPerShare: 5.46, leverage: 5 },
  { ticker: 'MSFT34', marginPerShare: 20.32, leverage: 5 },
  { ticker: 'ODPV3', marginPerShare: 2.27, leverage: 5 },
  { ticker: 'ORVR3', marginPerShare: 14.86, leverage: 5 },
  { ticker: 'PGMN3', marginPerShare: 1.37, leverage: 5 },
  { ticker: 'RAPT4', marginPerShare: 1.36, leverage: 5 },
  { ticker: 'RENT4', marginPerShare: 9.49, leverage: 5 },
  { ticker: 'SBFG3', marginPerShare: 3.07, leverage: 5 },
  { ticker: 'SIMH3', marginPerShare: 1.34, leverage: 5 },
  { ticker: 'SLCE3', marginPerShare: 3.20, leverage: 5 },
  { ticker: 'SMTO3', marginPerShare: 3.12, leverage: 5 },
  { ticker: 'VULC3', marginPerShare: 3.61, leverage: 5 },
  { ticker: 'RAIZ4', marginPerShare: 0.22, leverage: 4 },
  
  // Sem alavancagem (1x)
  { ticker: 'A1MD34', marginPerShare: 163.51, leverage: 1 },
  { ticker: 'AAPL34', marginPerShare: 66.87, leverage: 1 },
  { ticker: 'ABCB4', marginPerShare: 26.87, leverage: 1 },
  { ticker: 'AUAU3', marginPerShare: 3.35, leverage: 1 },
  { ticker: 'BABA34', marginPerShare: 32.55, leverage: 1 },
  { ticker: 'BHIA3', marginPerShare: 3.39, leverage: 1 },
  { ticker: 'BIAU39', marginPerShare: 131.50, leverage: 1 },
  { ticker: 'BOVB11', marginPerShare: 188.74, leverage: 1 },
  { ticker: 'BOVX11', marginPerShare: 18.89, leverage: 1 },
  { ticker: 'BRSR6', marginPerShare: 18.69, leverage: 1 },
  { ticker: 'BSLV39', marginPerShare: 184.00, leverage: 1 },
  { ticker: 'DESK3', marginPerShare: 14.51, leverage: 1 },
  { ticker: 'DXCO3', marginPerShare: 6.09, leverage: 1 },
  { ticker: 'GUAR3', marginPerShare: 9.71, leverage: 1 },
  { ticker: 'HBSA3', marginPerShare: 4.02, leverage: 1 },
  { ticker: 'ITLC34', marginPerShare: 41.64, leverage: 1 },
  { ticker: 'KLBN4', marginPerShare: 3.93, leverage: 1 },
  { ticker: 'LEVE3', marginPerShare: 34.74, leverage: 1 },
  { ticker: 'LWSA3', marginPerShare: 5.00, leverage: 1 },
  { ticker: 'MDIA3', marginPerShare: 25.32, leverage: 1 },
  { ticker: 'MILS3', marginPerShare: 15.60, leverage: 1 },
  { ticker: 'MYPK3', marginPerShare: 11.05, leverage: 1 },
  { ticker: 'NFLX34', marginPerShare: 8.81, leverage: 1 },
  { ticker: 'ONCO3', marginPerShare: 2.55, leverage: 1 },
  { ticker: 'P2LT34', marginPerShare: 276.21, leverage: 1 },
  { ticker: 'PLPL3', marginPerShare: 15.24, leverage: 1 },
  { ticker: 'RCSL4', marginPerShare: 7.60, leverage: 1 },
  { ticker: 'SEER3', marginPerShare: 12.05, leverage: 1 },
  { ticker: 'TFCO4', marginPerShare: 16.03, leverage: 1 },
  { ticker: 'TSMC34', marginPerShare: 222.10, leverage: 1 },
  { ticker: 'TUPY3', marginPerShare: 13.35, leverage: 1 },
  { ticker: 'UNIP6', marginPerShare: 62.86, leverage: 1 },
];

// Helper to find asset by ticker
export function findBTGAsset(ticker: string): BTGAsset | undefined {
  return btgAssets.find(a => a.ticker.toUpperCase() === ticker.toUpperCase());
}

// Get all tickers for autocomplete
export function getBTGTickers(): string[] {
  return btgAssets.map(a => a.ticker);
}

// Get margin required for a given quantity
export function calculateMarginRequired(ticker: string, quantity: number): number | null {
  const asset = findBTGAsset(ticker);
  if (!asset) return null;
  return asset.marginPerShare * quantity;
}
