/**
 * NinjaTrader Asset Database
 * Based on official NinjaTrader margin requirements
 * https://ninjatrader.com/pricing/margins/
 */

export interface NinjaTraderAsset {
  symbol: string;
  name: string;
  exchange: string;
  group: string;
  dayMargin: number;        // Day trading margin
  initialMargin: number;    // Overnight/initial margin
  tickSize: number;         // Minimum price movement
  tickValue: number;        // Value per tick
  pointValue: number;       // Value per point
  currency: 'USD' | 'EUR';
}

export const NINJATRADER_ASSETS: NinjaTraderAsset[] = [
  // ============ MICRO INDICES ============
  {
    symbol: 'MES',
    name: 'Micro E-mini S&P 500',
    exchange: 'CME',
    group: 'Micro Indices',
    dayMargin: 50,
    initialMargin: 2498.60,
    tickSize: 0.25,
    tickValue: 1.25,
    pointValue: 5,
    currency: 'USD',
  },
  {
    symbol: 'MNQ',
    name: 'Micro E-mini NASDAQ-100',
    exchange: 'CME',
    group: 'Micro Indices',
    dayMargin: 100,
    initialMargin: 3686.57,
    tickSize: 0.25,
    tickValue: 0.50,
    pointValue: 2,
    currency: 'USD',
  },
  {
    symbol: 'M2K',
    name: 'Micro E-mini Russell 2000',
    exchange: 'CME',
    group: 'Micro Indices',
    dayMargin: 50,
    initialMargin: 1045.02,
    tickSize: 0.10,
    tickValue: 0.50,
    pointValue: 5,
    currency: 'USD',
  },
  {
    symbol: 'MYM',
    name: 'Micro E-mini Dow',
    exchange: 'CME',
    group: 'Micro Indices',
    dayMargin: 50,
    initialMargin: 1567.71,
    tickSize: 1.00,
    tickValue: 0.50,
    pointValue: 0.50,
    currency: 'USD',
  },
  {
    symbol: 'MMC',
    name: 'Micro E-mini S&P MidCap 400',
    exchange: 'CME',
    group: 'Micro Indices',
    dayMargin: 50,
    initialMargin: 2523.08,
    tickSize: 0.10,
    tickValue: 1.00,
    pointValue: 10,
    currency: 'USD',
  },
  {
    symbol: 'MSC',
    name: 'Micro E-mini S&P SmallCap 600',
    exchange: 'CME',
    group: 'Micro Indices',
    dayMargin: 50,
    initialMargin: 1294.95,
    tickSize: 0.10,
    tickValue: 1.00,
    pointValue: 10,
    currency: 'USD',
  },
  {
    symbol: 'MNK',
    name: 'Micro Nikkei Stock Average',
    exchange: 'CME',
    group: 'Micro Indices',
    dayMargin: 50,
    initialMargin: 1974.06,
    tickSize: 5.00,
    tickValue: 0.50,
    pointValue: 0.10,
    currency: 'USD',
  },

  // ============ E-MINI INDICES ============
  {
    symbol: 'ES',
    name: 'E-Mini S&P 500',
    exchange: 'CME',
    group: 'E-Mini Indices',
    dayMargin: 500,
    initialMargin: 24985.95,
    tickSize: 0.25,
    tickValue: 12.50,
    pointValue: 50,
    currency: 'USD',
  },
  {
    symbol: 'NQ',
    name: 'E-Mini NASDAQ 100',
    exchange: 'CME',
    group: 'E-Mini Indices',
    dayMargin: 1000,
    initialMargin: 36865.75,
    tickSize: 0.25,
    tickValue: 5.00,
    pointValue: 20,
    currency: 'USD',
  },
  {
    symbol: 'RTY',
    name: 'E-Mini Russell 2000',
    exchange: 'CME',
    group: 'E-Mini Indices',
    dayMargin: 500,
    initialMargin: 10450.22,
    tickSize: 0.10,
    tickValue: 5.00,
    pointValue: 50,
    currency: 'USD',
  },
  {
    symbol: 'YM',
    name: 'E-Mini Dow',
    exchange: 'CBOT',
    group: 'E-Mini Indices',
    dayMargin: 500,
    initialMargin: 15677.13,
    tickSize: 1.00,
    tickValue: 5.00,
    pointValue: 5,
    currency: 'USD',
  },

  // ============ CURRENCIES ============
  {
    symbol: '6A',
    name: 'Australian Dollar',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 500,
    initialMargin: 2420,
    tickSize: 0.0001,
    tickValue: 10.00,
    pointValue: 100000,
    currency: 'USD',
  },
  {
    symbol: '6B',
    name: 'British Pound',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 500,
    initialMargin: 2200,
    tickSize: 0.0001,
    tickValue: 6.25,
    pointValue: 62500,
    currency: 'USD',
  },
  {
    symbol: '6C',
    name: 'Canadian Dollar',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 500,
    initialMargin: 1210,
    tickSize: 0.0001,
    tickValue: 10.00,
    pointValue: 100000,
    currency: 'USD',
  },
  {
    symbol: '6E',
    name: 'Euro FX',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 500,
    initialMargin: 3190,
    tickSize: 0.00005,
    tickValue: 6.25,
    pointValue: 125000,
    currency: 'USD',
  },
  {
    symbol: '6J',
    name: 'Japanese Yen',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 500,
    initialMargin: 3410,
    tickSize: 0.0000005,
    tickValue: 6.25,
    pointValue: 12500000,
    currency: 'USD',
  },
  {
    symbol: '6L',
    name: 'Brazilian Real',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 500,
    initialMargin: 1210,
    tickSize: 0.00005,
    tickValue: 5.00,
    pointValue: 100000,
    currency: 'USD',
  },
  {
    symbol: '6M',
    name: 'Mexican Peso',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 500,
    initialMargin: 1430,
    tickSize: 0.00001,
    tickValue: 5.00,
    pointValue: 500000,
    currency: 'USD',
  },
  {
    symbol: '6N',
    name: 'New Zealand Dollar',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 500,
    initialMargin: 1540,
    tickSize: 0.0001,
    tickValue: 10.00,
    pointValue: 100000,
    currency: 'USD',
  },
  {
    symbol: '6S',
    name: 'Swiss Franc',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 500,
    initialMargin: 4950,
    tickSize: 0.0001,
    tickValue: 12.50,
    pointValue: 125000,
    currency: 'USD',
  },
  {
    symbol: 'M6A',
    name: 'E-Micro Australian Dollar',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 50,
    initialMargin: 209,
    tickSize: 0.0001,
    tickValue: 1.00,
    pointValue: 10000,
    currency: 'USD',
  },
  {
    symbol: 'M6B',
    name: 'E-Micro British Pound',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 50,
    initialMargin: 220,
    tickSize: 0.0001,
    tickValue: 0.625,
    pointValue: 6250,
    currency: 'USD',
  },
  {
    symbol: 'M6E',
    name: 'E-Micro Euro',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 50,
    initialMargin: 297,
    tickSize: 0.0001,
    tickValue: 1.25,
    pointValue: 12500,
    currency: 'USD',
  },
  {
    symbol: 'MJY',
    name: 'E-Micro Japanese Yen',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 50,
    initialMargin: 308,
    tickSize: 0.000001,
    tickValue: 1.25,
    pointValue: 1250000,
    currency: 'USD',
  },
  {
    symbol: 'MCD',
    name: 'E-Micro Canadian Dollar',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 50,
    initialMargin: 110,
    tickSize: 0.0001,
    tickValue: 1.00,
    pointValue: 10000,
    currency: 'USD',
  },
  {
    symbol: 'MSF',
    name: 'E-Micro Swiss Franc',
    exchange: 'CME',
    group: 'Currencies',
    dayMargin: 50,
    initialMargin: 495,
    tickSize: 0.0001,
    tickValue: 1.25,
    pointValue: 12500,
    currency: 'USD',
  },

  // ============ ENERGIES ============
  {
    symbol: 'CL',
    name: 'Crude Oil',
    exchange: 'NYMEX',
    group: 'Energies',
    dayMargin: 1000,
    initialMargin: 4687.83,
    tickSize: 0.01,
    tickValue: 10.00,
    pointValue: 1000,
    currency: 'USD',
  },
  {
    symbol: 'MCL',
    name: 'Micro Crude Oil',
    exchange: 'NYMEX',
    group: 'Energies',
    dayMargin: 100,
    initialMargin: 470.99,
    tickSize: 0.01,
    tickValue: 1.00,
    pointValue: 100,
    currency: 'USD',
  },
  {
    symbol: 'NG',
    name: 'Natural Gas',
    exchange: 'NYMEX',
    group: 'Energies',
    dayMargin: 1000,
    initialMargin: 12697,
    tickSize: 0.001,
    tickValue: 10.00,
    pointValue: 10000,
    currency: 'USD',
  },
  {
    symbol: 'MNG',
    name: 'Micro Henry Hub Natural Gas',
    exchange: 'NYMEX',
    group: 'Energies',
    dayMargin: 100,
    initialMargin: 457.12,
    tickSize: 0.001,
    tickValue: 1.00,
    pointValue: 1000,
    currency: 'USD',
  },
  {
    symbol: 'HO',
    name: 'Heating Oil',
    exchange: 'NYMEX',
    group: 'Energies',
    dayMargin: 1000,
    initialMargin: 7050.18,
    tickSize: 0.0001,
    tickValue: 4.20,
    pointValue: 42000,
    currency: 'USD',
  },
  {
    symbol: 'RB',
    name: 'RBOB Gasoline',
    exchange: 'NYMEX',
    group: 'Energies',
    dayMargin: 1000,
    initialMargin: 5009.33,
    tickSize: 0.0001,
    tickValue: 4.20,
    pointValue: 42000,
    currency: 'USD',
  },
  {
    symbol: 'BZ',
    name: 'Brent Crude Last Day',
    exchange: 'NYMEX',
    group: 'Energies',
    dayMargin: 1000,
    initialMargin: 4679.82,
    tickSize: 0.01,
    tickValue: 10.00,
    pointValue: 1000,
    currency: 'USD',
  },
  {
    symbol: 'QM',
    name: 'E-Mini Crude Oil',
    exchange: 'NYMEX',
    group: 'Energies',
    dayMargin: 500,
    initialMargin: 2354.91,
    tickSize: 0.025,
    tickValue: 12.50,
    pointValue: 500,
    currency: 'USD',
  },
  {
    symbol: 'QG',
    name: 'E-Mini Natural Gas',
    exchange: 'NYMEX',
    group: 'Energies',
    dayMargin: 500,
    initialMargin: 1142.78,
    tickSize: 0.005,
    tickValue: 12.50,
    pointValue: 2500,
    currency: 'USD',
  },
  {
    symbol: 'QH',
    name: 'E-Mini Heating Oil',
    exchange: 'NYMEX',
    group: 'Energies',
    dayMargin: 500,
    initialMargin: 3529.71,
    tickSize: 0.0001,
    tickValue: 2.10,
    pointValue: 21000,
    currency: 'USD',
  },

  // ============ METALS ============
  {
    symbol: 'GC',
    name: 'Gold',
    exchange: 'COMEX',
    group: 'Metals',
    dayMargin: 2000,
    initialMargin: 29169.80,
    tickSize: 0.10,
    tickValue: 10.00,
    pointValue: 100,
    currency: 'USD',
  },
  {
    symbol: 'MGC',
    name: 'E-Micro Gold',
    exchange: 'COMEX',
    group: 'Metals',
    dayMargin: 200,
    initialMargin: 2917.20,
    tickSize: 0.10,
    tickValue: 1.00,
    pointValue: 10,
    currency: 'USD',
  },
  {
    symbol: 'SI',
    name: 'Silver',
    exchange: 'COMEX',
    group: 'Metals',
    dayMargin: 4000,
    initialMargin: 68464,
    tickSize: 0.005,
    tickValue: 25.00,
    pointValue: 5000,
    currency: 'USD',
  },
  {
    symbol: 'SIL',
    name: 'Micro Silver',
    exchange: 'COMEX',
    group: 'Metals',
    dayMargin: 1000,
    initialMargin: 13692.80,
    tickSize: 0.005,
    tickValue: 5.00,
    pointValue: 1000,
    currency: 'USD',
  },
  {
    symbol: 'HG',
    name: 'Copper',
    exchange: 'COMEX',
    group: 'Metals',
    dayMargin: 1000,
    initialMargin: 11000,
    tickSize: 0.0005,
    tickValue: 12.50,
    pointValue: 25000,
    currency: 'USD',
  },
  {
    symbol: 'MHG',
    name: 'Micro Copper',
    exchange: 'COMEX',
    group: 'Metals',
    dayMargin: 200,
    initialMargin: 1100,
    tickSize: 0.0005,
    tickValue: 1.25,
    pointValue: 2500,
    currency: 'USD',
  },
  {
    symbol: 'PL',
    name: 'Platinum',
    exchange: 'NYMEX',
    group: 'Metals',
    dayMargin: 2000,
    initialMargin: 17208.40,
    tickSize: 0.10,
    tickValue: 5.00,
    pointValue: 50,
    currency: 'USD',
  },
  {
    symbol: 'PA',
    name: 'Palladium',
    exchange: 'NYMEX',
    group: 'Metals',
    dayMargin: 2000,
    initialMargin: 31222.40,
    tickSize: 0.10,
    tickValue: 10.00,
    pointValue: 100,
    currency: 'USD',
  },
  {
    symbol: 'QC',
    name: 'E-Mini Copper',
    exchange: 'COMEX',
    group: 'Metals',
    dayMargin: 500,
    initialMargin: 5500,
    tickSize: 0.002,
    tickValue: 25.00,
    pointValue: 12500,
    currency: 'USD',
  },
  {
    symbol: 'QO',
    name: 'E-Mini Gold',
    exchange: 'COMEX',
    group: 'Metals',
    dayMargin: 500,
    initialMargin: 14686.10,
    tickSize: 0.25,
    tickValue: 12.50,
    pointValue: 50,
    currency: 'USD',
  },
  {
    symbol: 'QI',
    name: 'miNY Silver',
    exchange: 'COMEX',
    group: 'Metals',
    dayMargin: 1000,
    initialMargin: 34344.20,
    tickSize: 0.0125,
    tickValue: 31.25,
    pointValue: 2500,
    currency: 'USD',
  },
  {
    symbol: '1OZ',
    name: '1-Ounce Gold',
    exchange: 'COMEX',
    group: 'Metals',
    dayMargin: 50,
    initialMargin: 294.80,
    tickSize: 0.25,
    tickValue: 0.25,
    pointValue: 1,
    currency: 'USD',
  },

  // ============ CRYPTO ============
  {
    symbol: 'BTC',
    name: 'CME Bitcoin',
    exchange: 'CME',
    group: 'Crypto',
    dayMargin: 20000,
    initialMargin: 117585.60,
    tickSize: 5.00,
    tickValue: 25.00,
    pointValue: 5,
    currency: 'USD',
  },
  {
    symbol: 'MBT',
    name: 'Micro Bitcoin',
    exchange: 'CME',
    group: 'Crypto',
    dayMargin: 100,
    initialMargin: 2351.80,
    tickSize: 5.00,
    tickValue: 0.50,
    pointValue: 0.10,
    currency: 'USD',
  },
  {
    symbol: 'ETH',
    name: 'Ether',
    exchange: 'CME',
    group: 'Crypto',
    dayMargin: 2500,
    initialMargin: 52993.60,
    tickSize: 0.05,
    tickValue: 2.50,
    pointValue: 50,
    currency: 'USD',
  },
  {
    symbol: 'MET',
    name: 'Micro Ether',
    exchange: 'CME',
    group: 'Crypto',
    dayMargin: 50,
    initialMargin: 106.70,
    tickSize: 0.05,
    tickValue: 0.05,
    pointValue: 1,
    currency: 'USD',
  },
  {
    symbol: 'GSOL',
    name: 'CME Solana',
    exchange: 'CME',
    group: 'Crypto',
    dayMargin: 500,
    initialMargin: 28944.30,
    tickSize: 0.05,
    tickValue: 2.50,
    pointValue: 50,
    currency: 'USD',
  },
  {
    symbol: 'MSL',
    name: 'Micro Solana',
    exchange: 'CME',
    group: 'Crypto',
    dayMargin: 50,
    initialMargin: 1447.60,
    tickSize: 0.05,
    tickValue: 0.05,
    pointValue: 1,
    currency: 'USD',
  },
  {
    symbol: 'MXP',
    name: 'CME Micro XRP',
    exchange: 'CME',
    group: 'Crypto',
    dayMargin: 50,
    initialMargin: 2321,
    tickSize: 0.0001,
    tickValue: 0.50,
    pointValue: 5000,
    currency: 'USD',
  },
  {
    symbol: 'GXRP',
    name: 'CME XRP',
    exchange: 'CME',
    group: 'Crypto',
    dayMargin: 1000,
    initialMargin: 46415.60,
    tickSize: 0.0001,
    tickValue: 5.00,
    pointValue: 50000,
    currency: 'USD',
  },
  {
    symbol: 'BIT',
    name: 'Coinbase Nano Bitcoin',
    exchange: 'CFE',
    group: 'Crypto',
    dayMargin: 25,
    initialMargin: 379.50,
    tickSize: 1.00,
    tickValue: 0.01,
    pointValue: 0.01,
    currency: 'USD',
  },
  {
    symbol: 'ET',
    name: 'Coinbase Nano Ether',
    exchange: 'CFE',
    group: 'Crypto',
    dayMargin: 25,
    initialMargin: 162.80,
    tickSize: 0.10,
    tickValue: 0.01,
    pointValue: 0.10,
    currency: 'USD',
  },
  {
    symbol: 'SOL',
    name: 'Nano Solana (Coinbase)',
    exchange: 'CFE',
    group: 'Crypto',
    dayMargin: 500,
    initialMargin: 605,
    tickSize: 0.01,
    tickValue: 0.01,
    pointValue: 1,
    currency: 'USD',
  },
  {
    symbol: 'BTI',
    name: 'Coinbase Bitcoin Futures',
    exchange: 'CFE',
    group: 'Crypto',
    dayMargin: 10000,
    initialMargin: 38427.40,
    tickSize: 1.00,
    tickValue: 1.00,
    pointValue: 1,
    currency: 'USD',
  },
  {
    symbol: 'BCH',
    name: 'Bitcoin Cash',
    exchange: 'CFE',
    group: 'Crypto',
    dayMargin: 50,
    initialMargin: 356.40,
    tickSize: 0.10,
    tickValue: 0.01,
    pointValue: 0.10,
    currency: 'USD',
  },
  {
    symbol: 'DOG',
    name: 'Dogecoin',
    exchange: 'CFE',
    group: 'Crypto',
    dayMargin: 50,
    initialMargin: 1307.90,
    tickSize: 0.0001,
    tickValue: 0.50,
    pointValue: 5000,
    currency: 'USD',
  },
  {
    symbol: 'LC',
    name: 'Litecoin',
    exchange: 'CFE',
    group: 'Crypto',
    dayMargin: 50,
    initialMargin: 302.50,
    tickSize: 0.01,
    tickValue: 0.01,
    pointValue: 1,
    currency: 'USD',
  },

  // ============ FINANCIALS ============
  {
    symbol: 'ZB',
    name: 'US Treasury Bond',
    exchange: 'CBOT',
    group: 'Financials',
    dayMargin: 500,
    initialMargin: 4070,
    tickSize: 0.03125,
    tickValue: 31.25,
    pointValue: 1000,
    currency: 'USD',
  },
  {
    symbol: 'ZN',
    name: '10-Year T-Note',
    exchange: 'CBOT',
    group: 'Financials',
    dayMargin: 500,
    initialMargin: 2062.50,
    tickSize: 0.015625,
    tickValue: 15.625,
    pointValue: 1000,
    currency: 'USD',
  },
  {
    symbol: 'ZF',
    name: '5-Year T-Note',
    exchange: 'CBOT',
    group: 'Financials',
    dayMargin: 500,
    initialMargin: 1375,
    tickSize: 0.0078125,
    tickValue: 7.8125,
    pointValue: 1000,
    currency: 'USD',
  },
  {
    symbol: 'ZT',
    name: '2-Year T-Note',
    exchange: 'CBOT',
    group: 'Financials',
    dayMargin: 500,
    initialMargin: 1320,
    tickSize: 0.0078125,
    tickValue: 15.625,
    pointValue: 2000,
    currency: 'USD',
  },
  {
    symbol: 'TN',
    name: 'Ultra 10-Year T-Note',
    exchange: 'CBOT',
    group: 'Financials',
    dayMargin: 500,
    initialMargin: 2805,
    tickSize: 0.015625,
    tickValue: 15.625,
    pointValue: 1000,
    currency: 'USD',
  },
  {
    symbol: 'UB',
    name: 'Ultra US Treasury Bond',
    exchange: 'CBOT',
    group: 'Financials',
    dayMargin: 1000,
    initialMargin: 5665,
    tickSize: 0.03125,
    tickValue: 31.25,
    pointValue: 1000,
    currency: 'USD',
  },
  {
    symbol: 'TWE',
    name: '20yr US Treasury Bond',
    exchange: 'CBOT',
    group: 'Financials',
    dayMargin: 500,
    initialMargin: 4730,
    tickSize: 0.03125,
    tickValue: 31.25,
    pointValue: 1000,
    currency: 'USD',
  },
  {
    symbol: '10Y',
    name: 'Micro 10-Year Yield',
    exchange: 'CBOT',
    group: 'Financials',
    dayMargin: 50,
    initialMargin: 330,
    tickSize: 0.001,
    tickValue: 1.00,
    pointValue: 1000,
    currency: 'USD',
  },
  {
    symbol: '2YY',
    name: 'Micro 2-Year Yield',
    exchange: 'CBOT',
    group: 'Financials',
    dayMargin: 50,
    initialMargin: 363,
    tickSize: 0.001,
    tickValue: 1.00,
    pointValue: 1000,
    currency: 'USD',
  },
  {
    symbol: '5YY',
    name: 'Micro 5-Year Yield',
    exchange: 'CBOT',
    group: 'Financials',
    dayMargin: 50,
    initialMargin: 341,
    tickSize: 0.001,
    tickValue: 1.00,
    pointValue: 1000,
    currency: 'USD',
  },
  {
    symbol: '30Y',
    name: 'Micro 30-Year Yield',
    exchange: 'CBOT',
    group: 'Financials',
    dayMargin: 50,
    initialMargin: 297,
    tickSize: 0.001,
    tickValue: 1.00,
    pointValue: 1000,
    currency: 'USD',
  },
  {
    symbol: 'MTN',
    name: 'Micro Ultra 10yr Note',
    exchange: 'CBOT',
    group: 'Financials',
    dayMargin: 140.25,
    initialMargin: 280.50,
    tickSize: 0.015625,
    tickValue: 1.5625,
    pointValue: 100,
    currency: 'USD',
  },
  {
    symbol: 'MWN',
    name: 'Micro Ultra T-Bond',
    exchange: 'CBOT',
    group: 'Financials',
    dayMargin: 50,
    initialMargin: 566.50,
    tickSize: 0.03125,
    tickValue: 3.125,
    pointValue: 100,
    currency: 'USD',
  },
  {
    symbol: 'GE',
    name: 'Eurodollar',
    exchange: 'CME',
    group: 'Financials',
    dayMargin: 478.50,
    initialMargin: 957,
    tickSize: 0.005,
    tickValue: 12.50,
    pointValue: 2500,
    currency: 'USD',
  },
  {
    symbol: 'Z3N',
    name: '3 Year US Treasury Notes',
    exchange: 'CBOT',
    group: 'Financials',
    dayMargin: 1000,
    initialMargin: 2000,
    tickSize: 0.0078125,
    tickValue: 15.625,
    pointValue: 2000,
    currency: 'USD',
  },

  // ============ GRAINS ============
  {
    symbol: 'ZC',
    name: 'Corn',
    exchange: 'CBOT',
    group: 'Grains',
    dayMargin: 500,
    initialMargin: 1072.50,
    tickSize: 0.25,
    tickValue: 12.50,
    pointValue: 50,
    currency: 'USD',
  },
  {
    symbol: 'ZS',
    name: 'Soybeans',
    exchange: 'CBOT',
    group: 'Grains',
    dayMargin: 1000,
    initialMargin: 2200,
    tickSize: 0.25,
    tickValue: 12.50,
    pointValue: 50,
    currency: 'USD',
  },
  {
    symbol: 'ZW',
    name: 'Wheat',
    exchange: 'CBOT',
    group: 'Grains',
    dayMargin: 500,
    initialMargin: 1815,
    tickSize: 0.25,
    tickValue: 12.50,
    pointValue: 50,
    currency: 'USD',
  },
  {
    symbol: 'ZL',
    name: 'Soybean Oil',
    exchange: 'CBOT',
    group: 'Grains',
    dayMargin: 500,
    initialMargin: 2310,
    tickSize: 0.01,
    tickValue: 6.00,
    pointValue: 600,
    currency: 'USD',
  },
  {
    symbol: 'ZM',
    name: 'Soybean Meal',
    exchange: 'CBOT',
    group: 'Grains',
    dayMargin: 1000,
    initialMargin: 1705,
    tickSize: 0.10,
    tickValue: 10.00,
    pointValue: 100,
    currency: 'USD',
  },
  {
    symbol: 'ZO',
    name: 'Oats',
    exchange: 'CBOT',
    group: 'Grains',
    dayMargin: 1000,
    initialMargin: 1375,
    tickSize: 0.25,
    tickValue: 12.50,
    pointValue: 50,
    currency: 'USD',
  },
  {
    symbol: 'ZR',
    name: 'Rough Rice',
    exchange: 'CBOT',
    group: 'Grains',
    dayMargin: 1000,
    initialMargin: 1375,
    tickSize: 0.005,
    tickValue: 10.00,
    pointValue: 2000,
    currency: 'USD',
  },
  {
    symbol: 'MZC',
    name: 'Micro Corn',
    exchange: 'CBOT',
    group: 'Grains',
    dayMargin: 50,
    initialMargin: 107.80,
    tickSize: 0.125,
    tickValue: 1.25,
    pointValue: 10,
    currency: 'USD',
  },
  {
    symbol: 'MZS',
    name: 'Micro Soybean',
    exchange: 'CBOT',
    group: 'Grains',
    dayMargin: 50,
    initialMargin: 220,
    tickSize: 0.125,
    tickValue: 1.25,
    pointValue: 10,
    currency: 'USD',
  },
  {
    symbol: 'MZW',
    name: 'Micro Wheat',
    exchange: 'CBOT',
    group: 'Grains',
    dayMargin: 50,
    initialMargin: 181.50,
    tickSize: 0.125,
    tickValue: 1.25,
    pointValue: 10,
    currency: 'USD',
  },
  {
    symbol: 'MZL',
    name: 'Micro Soybean Oil',
    exchange: 'CBOT',
    group: 'Grains',
    dayMargin: 50,
    initialMargin: 231,
    tickSize: 0.01,
    tickValue: 0.60,
    pointValue: 60,
    currency: 'USD',
  },
  {
    symbol: 'MZM',
    name: 'Micro Soybean Meal',
    exchange: 'CBOT',
    group: 'Grains',
    dayMargin: 50,
    initialMargin: 170.50,
    tickSize: 0.10,
    tickValue: 1.00,
    pointValue: 10,
    currency: 'USD',
  },

  // ============ SOFTS ============
  {
    symbol: 'CC',
    name: 'Cocoa',
    exchange: 'ICE',
    group: 'Softs',
    dayMargin: 1000,
    initialMargin: 7084,
    tickSize: 1.00,
    tickValue: 10.00,
    pointValue: 10,
    currency: 'USD',
  },
  {
    symbol: 'KC',
    name: 'Coffee',
    exchange: 'ICE',
    group: 'Softs',
    dayMargin: 1000,
    initialMargin: 9610,
    tickSize: 0.05,
    tickValue: 18.75,
    pointValue: 375,
    currency: 'USD',
  },
  {
    symbol: 'CT',
    name: 'Cotton',
    exchange: 'ICE',
    group: 'Softs',
    dayMargin: 1000,
    initialMargin: 1254,
    tickSize: 0.01,
    tickValue: 5.00,
    pointValue: 500,
    currency: 'USD',
  },
  {
    symbol: 'SB',
    name: 'Sugar No. 11',
    exchange: 'ICE',
    group: 'Softs',
    dayMargin: 1000,
    initialMargin: 837,
    tickSize: 0.01,
    tickValue: 11.20,
    pointValue: 1120,
    currency: 'USD',
  },
  {
    symbol: 'OJ',
    name: 'Orange Juice',
    exchange: 'ICE',
    group: 'Softs',
    dayMargin: 1000,
    initialMargin: 4775,
    tickSize: 0.05,
    tickValue: 7.50,
    pointValue: 150,
    currency: 'USD',
  },
  {
    symbol: 'LBR',
    name: 'Lumber',
    exchange: 'CME',
    group: 'Softs',
    dayMargin: 1000,
    initialMargin: 1210,
    tickSize: 0.10,
    tickValue: 1.10,
    pointValue: 11,
    currency: 'USD',
  },
  {
    symbol: 'LBS',
    name: 'Random Length Lumber',
    exchange: 'CME',
    group: 'Softs',
    dayMargin: 1000,
    initialMargin: 5940,
    tickSize: 0.10,
    tickValue: 11.00,
    pointValue: 110,
    currency: 'USD',
  },

  // ============ MEATS ============
  {
    symbol: 'LE',
    name: 'Live Cattle',
    exchange: 'CME',
    group: 'Meats',
    dayMargin: 500,
    initialMargin: 3410,
    tickSize: 0.025,
    tickValue: 10.00,
    pointValue: 400,
    currency: 'USD',
  },
  {
    symbol: 'HE',
    name: 'Lean Hogs',
    exchange: 'CME',
    group: 'Meats',
    dayMargin: 1000,
    initialMargin: 1870,
    tickSize: 0.025,
    tickValue: 10.00,
    pointValue: 400,
    currency: 'USD',
  },
  {
    symbol: 'GF',
    name: 'Feeder Cattle',
    exchange: 'CME',
    group: 'Meats',
    dayMargin: 500,
    initialMargin: 5830,
    tickSize: 0.025,
    tickValue: 12.50,
    pointValue: 500,
    currency: 'USD',
  },

  // ============ EUREX (EUR) ============
  {
    symbol: 'FDAX',
    name: 'DAX Index',
    exchange: 'EUREX',
    group: 'EUREX',
    dayMargin: 2000,
    initialMargin: 45030,
    tickSize: 1.00,
    tickValue: 25.00,
    pointValue: 25,
    currency: 'EUR',
  },
  {
    symbol: 'FDXM',
    name: 'Mini-DAX',
    exchange: 'EUREX',
    group: 'EUREX',
    dayMargin: 500,
    initialMargin: 9005,
    tickSize: 1.00,
    tickValue: 5.00,
    pointValue: 5,
    currency: 'EUR',
  },
  {
    symbol: 'FDXS',
    name: 'Micro DAX Index',
    exchange: 'EUREX',
    group: 'EUREX',
    dayMargin: 100,
    initialMargin: 1801,
    tickSize: 1.00,
    tickValue: 1.00,
    pointValue: 1,
    currency: 'EUR',
  },
  {
    symbol: 'FESX',
    name: 'Euro Stoxx 50',
    exchange: 'EUREX',
    group: 'EUREX',
    dayMargin: 1000,
    initialMargin: 4122,
    tickSize: 1.00,
    tickValue: 10.00,
    pointValue: 10,
    currency: 'EUR',
  },
  {
    symbol: 'FSXE',
    name: 'Micro EURO STOXX 50',
    exchange: 'EUREX',
    group: 'EUREX',
    dayMargin: 206,
    initialMargin: 412,
    tickSize: 1.00,
    tickValue: 1.00,
    pointValue: 1,
    currency: 'EUR',
  },
  {
    symbol: 'FGBL',
    name: 'Euro-Bund',
    exchange: 'EUREX',
    group: 'EUREX',
    dayMargin: 1000,
    initialMargin: 1952,
    tickSize: 0.01,
    tickValue: 10.00,
    pointValue: 1000,
    currency: 'EUR',
  },
  {
    symbol: 'FGBM',
    name: 'Euro-Bobl',
    exchange: 'EUREX',
    group: 'EUREX',
    dayMargin: 1000,
    initialMargin: 1064,
    tickSize: 0.01,
    tickValue: 10.00,
    pointValue: 1000,
    currency: 'EUR',
  },
  {
    symbol: 'FGBS',
    name: 'Euro-Schatz',
    exchange: 'EUREX',
    group: 'EUREX',
    dayMargin: 500,
    initialMargin: 388,
    tickSize: 0.005,
    tickValue: 5.00,
    pointValue: 1000,
    currency: 'EUR',
  },
  {
    symbol: 'FGBX',
    name: 'Euro-Buxl',
    exchange: 'EUREX',
    group: 'EUREX',
    dayMargin: 1000,
    initialMargin: 3786,
    tickSize: 0.02,
    tickValue: 20.00,
    pointValue: 1000,
    currency: 'EUR',
  },
  {
    symbol: 'FVS',
    name: 'VSTOXX',
    exchange: 'EUREX',
    group: 'EUREX',
    dayMargin: 1000,
    initialMargin: 284,
    tickSize: 0.05,
    tickValue: 5.00,
    pointValue: 100,
    currency: 'EUR',
  },
];

// Group assets by category
export const NINJATRADER_ASSET_GROUPS = [
  'Micro Indices',
  'E-Mini Indices',
  'Currencies',
  'Energies',
  'Metals',
  'Crypto',
  'Financials',
  'Grains',
  'Softs',
  'Meats',
  'EUREX',
] as const;

// Helper function to get asset by symbol
export function getAssetBySymbol(symbol: string): NinjaTraderAsset | undefined {
  return NINJATRADER_ASSETS.find((a) => a.symbol === symbol);
}

// Helper function to get assets by group
export function getAssetsByGroup(group: string): NinjaTraderAsset[] {
  return NINJATRADER_ASSETS.filter((a) => a.group === group);
}

// Calculate effective leverage based on estimated contract value
export function calculateEffectiveLeverage(
  asset: NinjaTraderAsset,
  estimatedPrice: number
): number {
  const contractValue = estimatedPrice * asset.pointValue;
  return contractValue / asset.dayMargin;
}

// Default exchange rate USD/BRL (user can update)
export const DEFAULT_EXCHANGE_RATE = 5.50;
