// Lista de Ativos Ações — XP Investimentos (B3 Alavancagem)
// Fonte: Lista de Ativos Ações Risk Pro - XP - Abril 2026

export interface XPAsset {
  ticker: string;
  dayTradeLeverage: number;
  swingTradeLeverage: number;
}

export type Modalidade = 'daytrade' | 'swing';

export const xpAssets: XPAsset[] = [
  { ticker: 'ABCB4', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'ABEV3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'AERI3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'AESB3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'AGRO3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'ALLD3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'ALOS3', dayTradeLeverage: 200, swingTradeLeverage: 12 },
  { ticker: 'ALPA4', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'ALPK3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'ALSO3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'AMAR3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'AMOB3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'ANIM3', dayTradeLeverage: 38, swingTradeLeverage: 9 },
  { ticker: 'ARML3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'ARZZ3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'ASAI3', dayTradeLeverage: 149, swingTradeLeverage: 14 },
  { ticker: 'AUAU3', dayTradeLeverage: 8, swingTradeLeverage: 8 },
  { ticker: 'AURE3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'AXIA3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'AXIA6', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'AZEV4', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'AZZA3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'B3SA3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'BBAS3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'BBDC3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'BBDC4', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'BBRK3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'BBSE3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'BEEF3', dayTradeLeverage: 112, swingTradeLeverage: 14 },
  { ticker: 'BIDI4', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'BIOM3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'BLAU3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'BMGB4', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'BMOB3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'BPAN4', dayTradeLeverage: 93, swingTradeLeverage: 10 },
  { ticker: 'BRAP3', dayTradeLeverage: 6, swingTradeLeverage: 6 },
  { ticker: 'BRAP4', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'BRAV3', dayTradeLeverage: 179, swingTradeLeverage: 8 },
  { ticker: 'BRDT3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'BRIT3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'BRML3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'BRSR6', dayTradeLeverage: 141, swingTradeLeverage: 14 },
  { ticker: 'BSEV3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'BTOW3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'CAML3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'CARD3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'CASH3', dayTradeLeverage: 2, swingTradeLeverage: 2 },
  { ticker: 'CBAV3', dayTradeLeverage: 172, swingTradeLeverage: 11 },
  { ticker: 'CCRO3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'CEAB3', dayTradeLeverage: 196, swingTradeLeverage: 11 },
  { ticker: 'CESP3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'CESP6', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'CIEL3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'CMIG3', dayTradeLeverage: 5, swingTradeLeverage: 5 },
  { ticker: 'CMIG4', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'CMIN3', dayTradeLeverage: 111, swingTradeLeverage: 12 },
  { ticker: 'CNTO3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'COGN3', dayTradeLeverage: 36, swingTradeLeverage: 12 },
  { ticker: 'CPFE3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'CPLE3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'CPLE5', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'CPLE6', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'CRFB3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'CSAN3', dayTradeLeverage: 101, swingTradeLeverage: 12 },
  { ticker: 'CSED3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'CSMG3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'CSNA3', dayTradeLeverage: 185, swingTradeLeverage: 11 },
  { ticker: 'CURY3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'CVCB3', dayTradeLeverage: 2, swingTradeLeverage: 2 },
  { ticker: 'CXSE3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'CYRE3', dayTradeLeverage: 200, swingTradeLeverage: 13 },
  { ticker: 'CYRE4', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'DASA3', dayTradeLeverage: 5, swingTradeLeverage: 5 },
  { ticker: 'DESK3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'DEXP3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'DIRR3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'DMMO3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'DOTZ3', dayTradeLeverage: 2, swingTradeLeverage: 2 },
  { ticker: 'DTEX3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'DXCO3', dayTradeLeverage: 5, swingTradeLeverage: 5 },
  { ticker: 'ECOR3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'EGIE3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'ELET3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'ELET6', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'EMBJ3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'EMBR3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'ENAT3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'ENEV3', dayTradeLeverage: 185, swingTradeLeverage: 8 },
  { ticker: 'ENJU3', dayTradeLeverage: 2, swingTradeLeverage: 2 },
  { ticker: 'EQTL3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'ESPA3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'ETER3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'EVEN3', dayTradeLeverage: 5, swingTradeLeverage: 5 },
  { ticker: 'EZTC3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'FESA4', dayTradeLeverage: 5, swingTradeLeverage: 5 },
  { ticker: 'FIQE3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'FLRY3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'GGBR3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'GGBR4', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'GGPS3', dayTradeLeverage: 200, swingTradeLeverage: 10 },
  { ticker: 'GMAT3', dayTradeLeverage: 46, swingTradeLeverage: 14 },
  { ticker: 'GNDI3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'GOAU3', dayTradeLeverage: 5, swingTradeLeverage: 5 },
  { ticker: 'GOAU4', dayTradeLeverage: 192, swingTradeLeverage: 14 },
  { ticker: 'GRND3', dayTradeLeverage: 45, swingTradeLeverage: 14 },
  { ticker: 'GUAR3', dayTradeLeverage: 105, swingTradeLeverage: 11 },
  { ticker: 'HBOR3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'HBRE3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'HBSA3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'HGTX3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'HYPE3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'IGTA3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'INTB3', dayTradeLeverage: 189, swingTradeLeverage: 9 },
  { ticker: 'IRBR3', dayTradeLeverage: 145, swingTradeLeverage: 7 },
  { ticker: 'ISAE4', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'ITSA3', dayTradeLeverage: 6, swingTradeLeverage: 6 },
  { ticker: 'ITSA4', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'ITUB3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'ITUB4', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'JALL3', dayTradeLeverage: 5, swingTradeLeverage: 5 },
  { ticker: 'JHSF3', dayTradeLeverage: 172, swingTradeLeverage: 11 },
  { ticker: 'JPSA3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'JSLG3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'KEPL3', dayTradeLeverage: 70, swingTradeLeverage: 7 },
  { ticker: 'KLBN3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'KLBN4', dayTradeLeverage: 6, swingTradeLeverage: 6 },
  { ticker: 'LAME3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'LAME4', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'LAND3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'LAVV3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'LCAM3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'LEVE3', dayTradeLeverage: 50, swingTradeLeverage: 5 },
  { ticker: 'LINX3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'LJQQ3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'LOGG3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'LPSB3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'LREN3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'LVTC3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'LWSA3', dayTradeLeverage: 11, swingTradeLeverage: 11 },
  { ticker: 'MATD3', dayTradeLeverage: 5, swingTradeLeverage: 5 },
  { ticker: 'MBLY3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'MDIA3', dayTradeLeverage: 56, swingTradeLeverage: 6 },
  { ticker: 'MDNE3', dayTradeLeverage: 100, swingTradeLeverage: 10 },
  { ticker: 'MEAL3', dayTradeLeverage: 2, swingTradeLeverage: 2 },
  { ticker: 'MELK3', dayTradeLeverage: 5, swingTradeLeverage: 5 },
  { ticker: 'MGLU3', dayTradeLeverage: 169, swingTradeLeverage: 8 },
  { ticker: 'MILS3', dayTradeLeverage: 141, swingTradeLeverage: 14 },
  { ticker: 'MLAS3', dayTradeLeverage: 2, swingTradeLeverage: 2 },
  { ticker: 'MOSI3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'MOTV3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'MOVI3', dayTradeLeverage: 196, swingTradeLeverage: 11 },
  { ticker: 'MRVE3', dayTradeLeverage: 145, swingTradeLeverage: 14 },
  { ticker: 'MTRE3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'MULT3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'MYPK3', dayTradeLeverage: 141, swingTradeLeverage: 14 },
  { ticker: 'NATU3', dayTradeLeverage: 149, swingTradeLeverage: 14 },
  { ticker: 'NEOE3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'NGRD3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'NTCO3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'ODPV3', dayTradeLeverage: 141, swingTradeLeverage: 14 },
  { ticker: 'OMGE3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'OPCT3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'ORVR3', dayTradeLeverage: 200, swingTradeLeverage: 12 },
  { ticker: 'PARD3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'PCAR3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'PCAR4', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'PDTC3', dayTradeLeverage: 2, swingTradeLeverage: 2 },
  { ticker: 'PETR3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'PETR4', dayTradeLeverage: 312, swingTradeLeverage: 14 },
  { ticker: 'PETZ3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'PFRM3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'PGMN3', dayTradeLeverage: 128, swingTradeLeverage: 14 },
  { ticker: 'PINE4', dayTradeLeverage: 2, swingTradeLeverage: 2 },
  { ticker: 'PLPL3', dayTradeLeverage: 141, swingTradeLeverage: 14 },
  { ticker: 'PMAM3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'PNVL3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'POMO3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'POMO4', dayTradeLeverage: 119, swingTradeLeverage: 14 },
  { ticker: 'PORT3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'POSI3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'POWE3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'PRIO3', dayTradeLeverage: 179, swingTradeLeverage: 8 },
  { ticker: 'PRNR3', dayTradeLeverage: 5, swingTradeLeverage: 5 },
  { ticker: 'PSSA3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'PTBL3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'QUAL3', dayTradeLeverage: 6, swingTradeLeverage: 6 },
  { ticker: 'RADL3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'RAIL3', dayTradeLeverage: 200, swingTradeLeverage: 10 },
  { ticker: 'RANI3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'RAPT4', dayTradeLeverage: 133, swingTradeLeverage: 14 },
  { ticker: 'RDOR3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'RECV3', dayTradeLeverage: 159, swingTradeLeverage: 7 },
  { ticker: 'RENT3', dayTradeLeverage: 200, swingTradeLeverage: 13 },
  { ticker: 'RENT4', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'RIAA3', dayTradeLeverage: 105, swingTradeLeverage: 11 },
  { ticker: 'RLOG3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'ROMI3', dayTradeLeverage: 2, swingTradeLeverage: 2 },
  { ticker: 'RPMG3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'RRRP3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'RSID3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'SANB3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'SANB4', dayTradeLeverage: 2, swingTradeLeverage: 2 },
  { ticker: 'SAPR3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'SAPR4', dayTradeLeverage: 56, swingTradeLeverage: 6 },
  { ticker: 'SBFG3', dayTradeLeverage: 200, swingTradeLeverage: 11 },
  { ticker: 'SBSP3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'SEER3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'SEQL3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'SGPS3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'SHOW3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'SHUL4', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'SIMH3', dayTradeLeverage: 109, swingTradeLeverage: 12 },
  { ticker: 'SLCE3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'SMFT3', dayTradeLeverage: 200, swingTradeLeverage: 11 },
  { ticker: 'SMLS3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'SMTO3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'SOJA3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'SOMA3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'SQIA3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'SRNA3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'SULA4', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'SUZB3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'SYNE3', dayTradeLeverage: 2, swingTradeLeverage: 2 },
  { ticker: 'TAEE4', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'TASA3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'TASA4', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'TCSA3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'TECN3', dayTradeLeverage: 2, swingTradeLeverage: 2 },
  { ticker: 'TEND3', dayTradeLeverage: 200, swingTradeLeverage: 12 },
  { ticker: 'TGMA3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'TIET4', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'TIMP3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'TIMS3', dayTradeLeverage: 200, swingTradeLeverage: 13 },
  { ticker: 'TOTS3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'TPIS3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'TRAD3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'TRIS3', dayTradeLeverage: 5, swingTradeLeverage: 5 },
  { ticker: 'TRPL4', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'TTEN3', dayTradeLeverage: 93, swingTradeLeverage: 10 },
  { ticker: 'TUPY3', dayTradeLeverage: 50, swingTradeLeverage: 5 },
  { ticker: 'UCAS3', dayTradeLeverage: 2, swingTradeLeverage: 2 },
  { ticker: 'UGPA3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'UNIP3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'UNIP6', dayTradeLeverage: 58, swingTradeLeverage: 6 },
  { ticker: 'USIM3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'USIM5', dayTradeLeverage: 128, swingTradeLeverage: 11 },
  { ticker: 'VALE3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'VAMO3', dayTradeLeverage: 35, swingTradeLeverage: 11 },
  { ticker: 'VBBR3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'VIIA3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'VITT3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'VIVA3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'VIVR3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'VIVT3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'VIVT4', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'VLID3', dayTradeLeverage: 56, swingTradeLeverage: 6 },
  { ticker: 'VULC3', dayTradeLeverage: 125, swingTradeLeverage: 13 },
  { ticker: 'VVAR3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'VVEO3', dayTradeLeverage: 3, swingTradeLeverage: 3 },
  { ticker: 'WEGE3', dayTradeLeverage: 200, swingTradeLeverage: 14 },
  { ticker: 'WEST3', dayTradeLeverage: 2, swingTradeLeverage: 2 },
  { ticker: 'WIZC3', dayTradeLeverage: 4, swingTradeLeverage: 4 },
  { ticker: 'WIZS3', dayTradeLeverage: 1, swingTradeLeverage: 1 },
  { ticker: 'YDUQ3', dayTradeLeverage: 200, swingTradeLeverage: 11 },
];

// Helper to find asset by ticker
export function findXPAsset(ticker: string): XPAsset | undefined {
  return xpAssets.find(a => a.ticker.toUpperCase() === ticker.toUpperCase());
}

// Alias for findXPAsset
export function getXPAsset(ticker: string): XPAsset | undefined {
  return findXPAsset(ticker);
}

// Get all tickers for autocomplete
export function getXPTickers(): string[] {
  return xpAssets.map(a => a.ticker);
}

// Get leverage for a given ticker and modalidade
export function getXPLeverage(ticker: string, modalidade: Modalidade): number {
  const asset = findXPAsset(ticker);
  if (!asset) return 1;
  return modalidade === 'daytrade' ? asset.dayTradeLeverage : asset.swingTradeLeverage;
}

// Calcula deságio (%) = (1 / alavancagem) * 100
export function getDesagio(leverage: number): number {
  if (leverage <= 0) return 100;
  return (1 / leverage) * 100;
}

// Calcula margem por ação = preço / alavancagem
export function getMargemPorAcao(ticker: string, preco: number, modalidade: Modalidade): number {
  const leverage = getXPLeverage(ticker, modalidade);
  if (leverage <= 0) return preco;
  return preco / leverage;
}
