project_id = "ruicvcblxasrvocwepkl"

[functions.kiwify-webhook]
verify_jwt = false

[functions.upload-video]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.admin-manage-users]
verify_jwt = true